version: '3'

services:
  cosmos-api:
    build: .
    container_name: cosmos-api
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: cosmos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: