version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # Celery uses this
      - "15672:15672"   # RabbitMQ UI (http://<EC2>:15672)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"     # Celery result backend (optional)
    volumes:
      - redis_data:/data

volumes:
  rabbitmq_data:
  redis_data: